version: '3.5'

services:
  postgres:
    container_name: postgres-fastify
    image: postgres:14
    restart: always
    ports:
      - 7432:5432
    networks:
      - database
    volumes:
      - postgres-fastify:/var/lib/postgresql/data
      - ./conf/postgres/1-create-user-and-db.sh:/docker-entrypoint-initdb.d/1-create-user-and-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'Europe/Rome'
      PGTZ: 'Europe/Rome'

networks:
  database:
    name: database

volumes:
  postgres-fastify:
    name: postgres-fastify
